# Generated by Django 5.0.7 on 2024-08-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_teams_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
